# Generated by Django 4.2.11 on 2024-05-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='carma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='carma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
