# Generated by Django 4.2.11 on 2024-05-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_alter_questionlike_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='./uploads/avatars/avatar.JPG', upload_to='./uploads/avatars/'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
