# Generated by Django 4.2.11 on 2024-05-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_avatar_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='./static/avatars/avatar.JPG', upload_to='./static/avatars/'),
        ),
    ]
