# Generated by Django 4.2.11 on 2024-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/IMG_0895_R2b9IEo.png', upload_to='avatars/'),
        ),
    ]
