# Generated by Django 4.2.11 on 2024-05-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='truth_checkbox',
        ),
    ]
