# Generated by Django 4.2.11 on 2024-05-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_answer_truth_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='title',
        ),
    ]
