# Generated by Django 4.2.11 on 2024-05-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_answer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_id',
            field=models.IntegerField(default=0),
        ),
    ]
