# Generated by Django 4.2.11 on 2024-05-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_answer_answer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_id',
        ),
    ]
